using System;
using System.Threading;
using UnityEngine;
using Unity.Cloud.HighPrecision.Runtime;
using Unity.Industry.Viewer.Assets;
using System.Threading.Tasks;
using System.Collections;

namespace Unity.Industry.Viewer.Streaming
{
    // This script manages the navigation options and player movement in a streaming session.
    // It handles the initialization, activation, and deactivation of different navigation options.
    // The script provides functionality for translating the player to a target position and rotation smoothly.
    // It includes event handlers for changing navigation options, following a presenter, and requesting the default home view.
    // The script integrates with Unity's MonoBehaviour for lifecycle management and coroutine handling.
    [DefaultExecutionOrder(90)]
    public class NavigationController : MonoBehaviour
    {
        public static Action<Vector3, Quaternion> PlayerTranslateTo;
        public static Action<bool> PauseCameraControl;
        public static Action<NavigationOption> OnNavigationOptionChanged;
        public static Action<NavigationOption> ChangeToNewNavigationOption;
        public static Action<DoubleBounds> FocusToPoint;
        public static Action<GameObject> FollowPresenter;
        public static Action RequestDefaultHomeView;
        public static Vector3? StartingPosition;
        public static NavigationOption CurrentNavigationOption => m_CurrentNavigationOption;
        public NavigationOption[] NavigationOptions => navigationOptions;
        
        public NavigationOption DefaultNavigationOption => defaultNavigationOption;
        
        [SerializeField]
        private NavigationOption defaultNavigationOption;
        
        [SerializeField]
        private NavigationOption[] navigationOptions;
        
        private static NavigationOption m_CurrentNavigationOption;
        
        private void Awake()
        {
            foreach (var navigationOption in navigationOptions)
            {
                navigationOption.Initialize();
                navigationOption.gameObject.SetActive(false);
            }
            
            if (defaultNavigationOption == null)
            {
                Debug.LogError("Default navigation option is not set.");
                gameObject.SetActive(false);
                return;
            }
        }

        private async Task Start()
        {
            ChangeToNewNavigationOption += SetNavigationOption;
            PlayerTranslateTo += OnPlayerRequestTranslateTo;
            FollowPresenter += OnFollowPresenter;
            FocusToPoint += OnFocusToPoint;
            RequestDefaultHomeView += OnRequestDefaultHomeView;
            StartingPosition = null;
            var isOnlineAsset = StreamingModelController.StreamingAsset.Value.Asset is not OfflineAsset;
            if (isOnlineAsset)
            {
                StartingPosition = await GetStartingPositionFromService();
            }
            
            SetNavigationOption(defaultNavigationOption);
            AssetsController.AssetSelected += OnAssetSelected;
        }
        
        private void OnDestroy()
        {
            ChangeToNewNavigationOption -= SetNavigationOption;
            PlayerTranslateTo -= OnPlayerRequestTranslateTo;
            FollowPresenter -= OnFollowPresenter;
            FocusToPoint -= OnFocusToPoint;
            RequestDefaultHomeView -= OnRequestDefaultHomeView;
            foreach (var navigationOption in navigationOptions)
            {
                navigationOption.Uninitialize();
            }
            AssetsController.AssetSelected -= OnAssetSelected;
        }
        
        private async Task<Vector3?> GetStartingPositionFromService()
        {
            try
            {
                var key = "Startingpoint";
                var query = StreamingModelController.StreamingAsset.Value.Asset.Metadata.Query()
                    .SelectWhereKeyEquals(key)
                    .ExecuteAsync(CancellationToken.None);
                
                await foreach (var item in query)
                {
                    if (item.Key == key)
                    {
                        var coords = item.Value.AsText().Value.Split(",");
                        if (coords.Length != 3)
                        {
                            return null;
                        }
                        if(float.TryParse(coords[0], out var x) && float.TryParse(coords[1], out var y) && float.TryParse(coords[2], out var z))
                        {
                            return new Vector3(x, y, z);
                        }

                        return null;
                    }
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning($"Failed to get starting position from service: {e.Message}");
                return null;
            }

            return null;
        }
        
        private void OnFocusToPoint(DoubleBounds bounds)
        {
            if(m_CurrentNavigationOption.GetNavigationGameObject() == null) return;
            m_CurrentNavigationOption?.FocusToPoint(bounds);
        }
        
        private void OnAssetSelected(AssetInfo obj)
        {
            PauseCameraControl?.Invoke(false);
        }

        private void OnRequestDefaultHomeView()
        {
            CurrentNavigationOption?.SetDefaultView();
        }

        private void OnFollowPresenter(GameObject presenter)
        {
            m_CurrentNavigationOption.FollowPresenter(presenter);
        }

        private void OnPlayerRequestTranslateTo(Vector3 targetPosition, Quaternion targetRotation)
        {
            m_CurrentNavigationOption.TranslateTo(targetPosition, targetRotation);
        }

        private void SetNavigationOption(NavigationOption navigationOption)
        {
            if (m_CurrentNavigationOption != null)
            {
                m_CurrentNavigationOption.OnNavigationOptionDisable();
                m_CurrentNavigationOption.gameObject.SetActive(false);
                if(m_CurrentNavigationOption.NavigationCamera != navigationOption.NavigationCamera)
                {
                    m_CurrentNavigationOption.NavigationCamera?.gameObject.SetActive(false);
                }
            }
            
            m_CurrentNavigationOption = navigationOption;
            m_CurrentNavigationOption.gameObject.SetActive(true);
            if (m_CurrentNavigationOption.NavigationCamera != null)
            {
                m_CurrentNavigationOption.NavigationCamera.gameObject.SetActive(true);
            }
            m_CurrentNavigationOption.OnNavigationOptionEnable();
            OnNavigationOptionChanged?.Invoke(m_CurrentNavigationOption);
        }
    }
}
